# Generated by Django 5.1 on 2024-08-16 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_level', models.IntegerField()),
                ('fit_sizing_level', models.IntegerField()),
                ('preferred_piece', models.CharField(max_length=100)),
                ('design_style', models.CharField(max_length=50)),
                ('material_quality', models.CharField(max_length=50)),
                ('predicted_fashion_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
